In [1]:
# Import Modules
from warnings import simplefilter
simplefilter(action='ignore', category=FutureWarning)
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SequentialFeatureSelector

# Display all of the columns
pd.set_option('display.max_columns', None)

In [2]:
# Read the CSV file into a Pandas DataFrame
df = pd.read_csv('./clean_data.csv')
df.head()

,Season Number,Startup Name,Episode Number,Pitch Number,Season Start,Original Air Date,Industry,Business Description,Pitchers Gender,US Viewership,Original Ask Amount,Original Offered Equity,Valuation Requested,Got Deal,Total Deal Amount,Total Deal Equity,Deal Valuation,Number of Sharks in Deal,Investment Amount Per Shark,Equity Per Shark,Royalty Deal,Barbara Corcoran Investment Amount,Barbara Corcoran Investment Equity,Mark Cuban Investment Amount,Mark Cuban Investment Equity,Lori Greiner Investment Amount,Lori Greiner Investment Equity,Robert Herjavec Investment Amount,Robert Herjavec Investment Equity,Daymond John Investment Amount,Daymond John Investment Equity,Kevin O Leary Investment Amount,Kevin O Leary Investment Equity,Guest Investment Amount,Guest Investment Equity,Guest Name,Barbara Corcoran Present,Mark Cuban Present,Lori Greiner Present,Robert Herjavec Present,Daymond John Present,Kevin O Leary Present,Guest Present,Has_Website,Barbara Corcoran Got Deal,Mark Cuban Got Deal,Lori Greiner Got Deal,Robert Herjavec Got Deal,Daymond John Got Deal,Kevin O Leary Got Deal
0,1,AvaTheElephant,1,1,2009-08-09,2009-08-09,Health/Wellness,Ava The Elephant - Baby and Child Care,Female,4.15,50000,15.0,333333,1,50000.0,55.0,90909.0,1.0,50000.0,55.0,0.0,50000.0,55.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0,1,0,0,0,0,0
1,1,Mr.Tod'sPieFactory,1,2,2009-08-09,2009-08-09,Food and Beverage,Mr. Tod's Pie Factory - Specialty Food,Male,4.15,460000,10.0,4600000,1,460000.0,50.0,920000.0,2.0,230000.0,25.0,0.0,230000.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,230000.0,25.0,0.0,0.0,0.0,0.0,NaN,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0,1,0,0,0,1,0
2,1,Wispots,1,3,2009-08-09,2009-08-09,Business Services,Wispots - Consumer Services,Male,4.15,1200000,10.0,12000000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0,0,0,0,0,0,0
3,1,CollegeFoxesPackingBoxes,1,4,2009-08-09,2009-08-09,Lifestyle/Home,College Foxes Packing Boxes - Consumer Services,Male,4.15,250000,25.0,1000000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0,0,0,0,0,0,0
4,1,IonicEar,1,5,2009-08-09,2009-08-09,Software/Tech,Ionic Ear - Novelties,Male,4.15,1000000,15.0,6666667,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1,0,0,0,0,0,0

In [ ]:
# # Split target column from dataset
# y = df['Got Deal']
# X = df.drop(columns='Got Deal')

In [ ]:
# X.columns

In [ ]:
# X1 = pd.DataFrame(X[[
# #       'Season Number',  
#        'Pitchers Gender', 
#        'US Viewership', 
#        'Original Ask Amount',
#        'Original Offered Equity',
# #        'Industry',
#         ]])
# #X1['Log Ask']=np.log(X['Original Ask Amount'])
# X1.head()

In [ ]:
# X1.shape

In [ ]:
# X1.dtypes

In [ ]:
# # Print first five entries for target
# y.head()

In [ ]:
# # Encode the categorical variables using get_dummies
# X1 = pd.get_dummies(X1)

In [ ]:
# # Preview the data
# X1.head()

In [ ]:
# X1.shape

In [5]:
# Select the columns that do not provide the answer to use in the feature selection
sharktank_df_limited = df.loc[:, ['Got Deal','Industry','Pitchers Gender','US Viewership', 'Original Ask Amount',
                                       'Original Offered Equity','Has_Website','Barbara Corcoran Present','Mark Cuban Present',
                                       'Lori Greiner Present','Robert Herjavec Present','Daymond John Present', 'Kevin O Leary Present', 
                                       'Guest Present',]]

In [6]:
# Split target column from dataset
y = sharktank_df_limited['Got Deal']
X2 = sharktank_df_limited.drop(columns='Got Deal')

In [7]:
X2.head()

,Industry,Pitchers Gender,US Viewership,Original Ask Amount,Original Offered Equity,Has_Website,Barbara Corcoran Present,Mark Cuban Present,Lori Greiner Present,Robert Herjavec Present,Daymond John Present,Kevin O Leary Present,Guest Present
0,Health/Wellness,Female,4.15,50000,15.0,0,1.0,0.0,0.0,1.0,1.0,1.0,0.0
1,Food and Beverage,Male,4.15,460000,10.0,0,1.0,0.0,0.0,1.0,1.0,1.0,0.0
2,Business Services,Male,4.15,1200000,10.0,0,1.0,0.0,0.0,1.0,1.0,1.0,0.0
3,Lifestyle/Home,Male,4.15,250000,25.0,0,1.0,0.0,0.0,1.0,1.0,1.0,0.0
4,Software/Tech,Male,4.15,1000000,15.0,1,1.0,0.0,0.0,1.0,1.0,1.0,0.0

In [9]:
# Encode the categorical variables using get_dummies
X2 = pd.get_dummies(X2)

In [10]:
# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X2, y)

In [11]:
X_train.shape

(1008, 30)

In [12]:
X_test.shape

(337, 30)

In [13]:
# Scale the training data
X_train_scaled = StandardScaler().fit_transform(X_train)
X_test_scaled = StandardScaler().fit_transform(X_test)

In [14]:
# Instantiate the model
model = KNeighborsClassifier(n_neighbors=40)

In [15]:
# Initialize Sequential Feature Selector
sfs = SequentialFeatureSelector(model, n_features_to_select='auto', direction='forward', scoring='accuracy', cv=5)

# Fit SFS to the data
sfs.fit(X_train_scaled, y_train)

# Get selected feature indices
selected_feature_indices = sfs.get_support(indices=True)

# Get selected feature names
selected_feature_names = X2.columns[selected_feature_indices]

# Subset the data with selected features
X_train_selected = X_train_scaled[:, selected_feature_indices]
X_test_selected = X_test_scaled[:, selected_feature_indices]

# Print selected feature indices and names
for index, name in zip(selected_feature_indices, selected_feature_names):
    print(f"Feature {index}: {name}")

Feature 0: US Viewership
Feature 2: Original Offered Equity
Feature 3: Has_Website
Feature 6: Lori Greiner Present
Feature 11: Industry_Automotive
Feature 12: Industry_Business Services
Feature 14: Industry_Electronics
Feature 16: Industry_Fitness/Sports/Outdoors
Feature 18: Industry_Green/CleanTech
Feature 21: Industry_Liquor/Alcohol
Feature 22: Industry_Media/Entertainment
Feature 23: Industry_Pet Products
Feature 24: Industry_Software/Tech
Feature 25: Industry_Travel
Feature 26: Industry_Uncertain/Other

In [16]:
# Train the model
model.fit(X_train_selected, y_train)

KNeighborsClassifier(n_neighbors=40)

In [17]:
# Create predictions
y_pred = model.predict(X_test_selected)

# # Review the predictions
# y_pred

In [18]:
# Print confusion matrix
confusion_matrix(y_pred,y_test)

array([[ 21,  27],
       [115, 174]], dtype=int64)

In [19]:
# Print classification report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.15      0.44      0.23        48
           1       0.87      0.60      0.71       289

    accuracy                           0.58       337
   macro avg       0.51      0.52      0.47       337
weighted avg       0.76      0.58      0.64       337